<?php

namespace AlsaJobsBundle\Repository;

/**
 * JobAdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobAdvertRepository extends \Doctrine\ORM\EntityRepository
{
}
